### Hello world
GET http://127.0.0.1:5000/hello HTTP/1.1

### get classify: error
GET http://127.0.0.1:5000/result?filename=aklahhubdw.paac.csvsadsa HTTP/1.1

### get classify: success
GET http://127.0.0.1:5000/result?filename=rhmbtqwag.paac.csv HTTP/1.1

### post : sequences
POST http://127.0.0.1:5000/upload-data/seq HTTP/1.1
content-type: application/json

{
    "seq": "ACSAG"
}